name = "solid-api"
main = "src/worker.ts"
workers_dev = true
account_id = "fa2a5e3787deead800c822a0e1171763"
compatibility_date = "2024-09-23"

[vars]
ENVIORNMENT = "production"
STYTCH_PROJECT_ID = ""
STYTCH_SECRET = ""
STYTCH_URL = ""
STYTCH_API = ""
SUPABASE_URL = ""
SUPABASE_KEY = ""
